# appspec.yml

version: 0.0
os: ubuntu
files:
  - source: /
    destination: /home/ubuntu/Fake_Profile_Detection
permissions:
  - object: /home/ubuntu/Fake_Profile_Detection
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/run_migrations.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
