# buildspec.yml

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests"
      - python manage.py runserver

artifacts:
  files: '**/*'
